---
title: "Final Project Overview"
author: "Carolina Torreblanca"
institute: "University of Pennsylvania"

format:
  revealjs:
    toc: false
    theme: [custom_iea.scss]
    width: 1050
    margin: 0.1
    logo: DevLab_Logo_29Mar2023.png
    footer: "https://carolina-torreblanca.github.io/psci3200-globaldev-main/"
    embed-resources: true
    template-partials:
    - title-slide.html
    gfm:
    mermaid-format: png
    code-line-numbers: false
editor: source

highlight-style: github

bibliography: img/references.bib
---


# Final Project Overview

## Objectives

*The final project is the culmination of this course*

- Reflect the substantive knowledge and technical skills that you developed
- Provide experience
  + Generating a research question
  + Refining into a testable hypothesis
  + Identifying data to provide evidence for or against
  + Communicating the results of your analysis to others

## Objectives

- Help you answer research questions in the future
- Assess the strength of evidence presented by others
- Incorporate research into your professional decision-making

## Requirements

- Research project with data of your choosing
  + Formulate a research question
  + Find data that can help you answer that question
  + Apply the tools and methods from this course
  + Write-up analysis
- Produce a webpage to present your results for public consumption 

## Write-up

1. Introduction to research question and data
2. Discussion of research design, assumptions, and threats to inference
3. Visualization describing your data
4. Presentation of results from a regression model and discussion of implications for research question 
5. Robustness test to probe assumptions or empirical extension
6. Discussion of policy implications
7. Appendix including supplementary materials

## Final Project Touchpoints

\

| Milestone                    | Due Date|
|:-----------------------------|:--------|
| [Create a GitHub repository](https://carolina-torreblanca.github.io/psci3200-globaldev-main/assignments/02_gitrepo.html)| Feb 17 |
| [Research Question and Data](https://carolina-torreblanca.github.io/psci3200-globaldev-main/assignments/03_fprqd.html)  | Feb 23 |
| [Research Design](https://carolina-torreblanca.github.io/psci3200-globaldev-main/assignments/04_fpdesign.html)          | Mar 5  |
| [Submit proposal](https://carolina-torreblanca.github.io/psci3200-globaldev-main/assignments/05_fptest.html)            | Apr 2  |
| [Submit final project](https://carolina-torreblanca.github.io/psci3200-globaldev-main/assignments/final_project.html)   | May 10 |

# What Makes a Good Research Question?

## Step 1: Find a question

\

The most important thing about a research question is that it is a **question**

::: incremental
- You do not know the answer. You could be wrong
- Adding a question mark to a topic does not make it a question
:::

## Step 1: Find a question

- "Girls' education?" -- not a question. This is a topic

::: incremental
- "Is girls' education important?" -- important how? To whom? Compared to what?

- "Does expanding secondary school access increase women's labor force participation?"
:::

## Step 2: What's your hypothesis?

You have a question. Now: what do you think the answer is, and why?

::: incremental
- Engage with what we already know. What has been studied? What do those studies find?
- Do you have a reason to think the answer might be different in a different place, at a different time, for a different population?
:::

## Step 3: Research design

How would you answer this?

::: incremental
- What is the counterfactual -- what are you comparing to what?
- What data would you need?
:::

## Step 4: Is this tractable?

Can you actually do this? Can one person do it in a semester?

::: incremental
- One outcome
- One mechanism
- One context
:::

# Let's build one together

## Topic: Climate change

Here are three things we know:

::: incremental
- [80% of people globally](https://climatepromise.undp.org/news-and-stories/worlds-largest-survey-climate-change-out-heres-what-results-show) want their governments to take stronger action on climate change (UNDP, 2024)
- Extreme weather events are [increasing in frequency and intensity](https://www.ipcc.ch/report/ar6/wg1/chapter/chapter-11/) -- more floods, droughts, heat waves (IPCC AR6)
- But developing countries need $310-365 billion/year in adaptation finance and [received only $26 billion in 2023](https://www.unep.org/resources/adaptation-gap-report-2025) (UNEP, 2025)
:::

## What is a research question here?

\

. . .

*Your turn*

## What is your hypothesis?

\

. . .

*Your turn*

## How would you test it?

If you were god and could run any experiment, what would you do?

. . .

Now come back to earth. What data would you need? Does it exist?

## Some data that exists

- [Yale Climate Opinion Maps](https://climatecommunication.yale.edu/visualizations-data/ycom-us/) -- public opinion on climate change across US counties
- [Afrobarometer](https://www.afrobarometer.org/data/) -- survey data across African countries including climate questions
- [EM-DAT](https://www.emdat.be/) -- international disaster database
- [World Bank Climate Change Data](https://data.worldbank.org/topic/climate-change) -- emissions, energy, land use by country
- [Notre Dame Global Adaptation Initiative](https://gain.nd.edu/our-work/country-index/) -- country-level climate vulnerability and readiness scores

## Past Student Projects

- [Chinese Development Loans and Corruption in Africa](https://glucier39.github.io/PSCI3200_Final/PSCI3200%20Final%20Project.html)
- [Civil Society, Repression, and Electoral Democracy](https://isaac21694.github.io/Isaac21694/)
- [Social Media Censorship and Political Action](https://norahtorious.github.io/PSCI3200_final_project/)

# Assignment 1: Research Question and Data

## Research Question and Data

**Must be submitted via Slack by 11:59pm EST on Monday, February 23**

- Sketch a research question that you'd like to investigate
- Identify data that can answer that question
- I will provide feedback on the viability of the questions, the suitability of the data, and the extent to which your general idea will meet my expectations

## Research Question and Data

*Send me a quarto html file that:*

- Briefly describes your idea for a research question
  + 3-4 sentences describing some relationship in the world that you want to investigate
  + This should involve at least two things in the world that can be measured with existing data
  + You may submit more than 1 idea
- Proposes data and measures that will help you answer it
  + Specific, existing dataset that you can access
  + Specific variables that will be used to answer the research question

## Types of data

- Election returns
  + Compilations of election data, such as [Constituency-Level Elections Archive (CLEA)](https://electiondataarchive.org/)
  + Returns for specific elections are often available from a country's electoral commission website
- Replication data
  + Published research from the last 5-10 years should make data publicly available, often on Harvard's Dataverse

## Types of data

- Survey data
  + Used extremely heavily in the social sciences: Afrobarometer, Latinobarometer, etc.
- Administrative data
  + Data on government or organization programs

The world is full of data. Look hard. Ask me if you can't find anything suitable

## Popular Public Datasets

**[Dataset of datasets](https://github.com/erikgahner/PolData/blob/master/PolData.csv)**

- [Varieties of Democracy](https://github.com/vdeminstitute/vdemdata)
- [World Bank Development/Governance Indicators](https://cran.r-project.org/web/packages/WDI/WDI.pdf)
- Demographic and Health Survey

# Assignment 2: Research Design

## Research Design

**Due March 5**

::: {style="font-size: 0.85em;"}
1. **Research question and background** (40%): Describe your research question and why it is interesting or important. Incorporate feedback from Assignment 1. Include references to at least two pieces of existing research -- academic articles, policy reports, think tank publications (e.g. Brookings, UNHCR), or data journalism. ~150-200 words

2. **Testable hypothesis** (25%): State at least one testable hypothesis. Describe a specific relationship you expect to see (i.e. changes in x cause changes in y). Make an argument for why, based on existing research or your own reasoning. ~150-200 words
:::

## Research Design

::: {style="font-size: 0.85em;"}
3. **Variables and visualization** (25%): Discuss the specific variables and dataset you will use. Mention the data source, unit of analysis, and sample. Create a `ggplot` to visualize the relationship between your variables. Good options: scatter plots (continuous), grouped bar charts (ordinal/binary), line graphs (time-series)

4. **Regression model** (10%): Specify the main regression model you will use to test your hypothesis. Use markdown to render the equation neatly
:::
